#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

motor[leftMotor] = -30;
motor[rightMotor] = 30;
wait1Msec(1937.5);/*
motor[leftMotor] = 0;
motor[rightMotor] = 0;
wait1Msec(1000);//----------*/
motor[leftMotor] = 28.5;
motor[rightMotor] = 30;
wait1Msec(5.873);
motor[leftMotor] = 0;
motor[rightMotor] = 0;

/*
clearTimer(T1);
while (time1[T1] < 1500)
{

	motor[leftMotor] = -30;
	motor[rightMotor] = 30;

}
*/

}
