#pragma config(Sensor, dgtl9,  rangerSensor,   sensorSONAR_inch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port6,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move_forward(int number_of_seconds, int speed);
void move_backward(int number_of_seconds, int speed);
void raise_arm(int number_of_seconds, int speed);

task main()
{

while (2 == 2)
{

				if(vexRT[Btn8L] == 1)
				{
					motor(leftMotor) = 60;
 					motor(rightMotor) = -60;
 					wait1Msec(2000);//almost 180
 					stopAllMotors();
				}
				else if (vexRT[Btn8U] == 1)
				{
					motor(leftMotor) = 60;
 					motor(rightMotor) = -60;
 					wait1Msec(1500);
 					stopAllMotors();
				}
				else if (vexRT[Btn8R] == 1)
				{
					motor(leftMotor) = 60;
 					motor(rightMotor) = -60;
 					wait1Msec(1000);
 					stopAllMotors();
				}
				else if (vexRT[Btn8D] == 1)
				{
					motor(leftMotor) = 60;
 					motor(rightMotor) = -60;
 					wait1Msec(500);
 					stopAllMotors();
				}




}
}







void move_forward(int number_of_seconds, int speed)
{
	motor[leftMotor] = speed;
  motor[rightMotor] = speed;
  wait1Msec(number_of_seconds*1000);
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
}

void move_backward(int number_of_seconds, int speed)
{
	motor[leftMotor] = speed * -1;
  motor[rightMotor] = speed * -1;
  wait1Msec(number_of_seconds*1000);
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
}

void raise_arm(int number_of_seconds, int speed)
{
	motor[armMotor] = speed;
  wait1Msec(number_of_seconds*1000);
  motor[armMotor] = 0;
}
