# Generated by Django 3.2.4 on 2021-06-29 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
