# Generated by Django 3.2.4 on 2021-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField(blank=True)),
            ],
        ),
    ]
