# Generated by Django 3.2.4 on 2021-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doge', '0002_abi'),
    ]

    operations = [
        migrations.AddField(
            model_name='abi',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
